### ISSUE TITLE
Fatal error: Copied file during build

### ISSUE THREAD

**Issue by jwoertink** [mllrsohn/grunt-node-webkit-builder#125] opened 2015-01-05 22:56 UTC
When I try building my app, I get this error:

```text
[14:48PM] ard-checkin-client$ grunt
Running "nodewebkit:osx" (nodewebkit) task
Using v0.11.5
Create cache folder in /Users/jeremy/Sites/alice/ard-checkin-client/cache/0.11.5
Using cache for: osx32
Create cache folder in /Users/jeremy/Sites/alice/ard-checkin-client/cache/0.11.5
Using cache for: osx64
Create release folder in /Users/jeremy/Sites/alice/ard-checkin-client/build/ard-checkin-client/osx32
Create release folder in /Users/jeremy/Sites/alice/ard-checkin-client/build/ard-checkin-client/osx64
chmod 16877 on /Users/jeremy/Sites/alice/ard-checkin-client/build/ard-checkin-client/osx32/ard-checkin-client.app failed after copying, ignoring
chmod 16877 on /Users/jeremy/Sites/alice/ard-checkin-client/build/ard-checkin-client/osx64/ard-checkin-client.app failed after copying, ignoring
Fatal error: Copied file (/Users/jeremy/Sites/alice/ard-checkin-client/build/ard-checkin-client/osx32/ard-checkin-client.app/Contents/Resources/nw.icns) doesn't exist in destination after copying
```

Here is my `Gruntfile.js`

```javascript
module.exports = function(grunt) {
  var pkg = grunt.file.readJSON('package.json');
  var VERSION = '0.11.5';

  grunt.initConfig({
    pkg: pkg,
    nodewebkit: {
      osx: {
        options: {
          version: VERSION,
          appName: pkg.name,
          appVersion: pkg.version,
          platforms: ['osx'],
          macIcns: './app/alice.icns'
        },
        src: ['./app/**']
      },
      win: {
        options: {
          version: VERSION,
          appName: pkg.name,
          appVersion: pkg.version,
          platforms: ['win'],
          winIco: './app/alice.ico'
        },
        src: ['./app/**']
      },
      all: {
        options: {
          version: VERSION,
          appName: pkg.name,
          appVersion: pkg.version,
          platforms: ['win', 'osx'],
          winIco: './app/alice.ico',
          macIcns: './app/alice.icns'
        },
        src: ['./app/**']
      }
    }
  });

  grunt.loadNpmTasks('grunt-node-webkit-builder');
  var target = grunt.option('target') || 'osx';
  grunt.registerTask('default', ['nodewebkit:'+target]);
};
```
I'm on OSX 10.9.5

Although the error happens, the default version of the node-webkit app still builds. I just don't see my version.

**Comment by sergiovilar** [comment] 2015-01-06 21:02
Same problem here.

**Comment by jwoertink** [comment] 2015-01-06 21:07
I noticed that if I keep running `grunt` it will eventually just work. I dropped back down to version `0.2.3` and it works every time.

**Comment by adam-lynch** [comment] 2015-01-08 19:52
Yeah :frowning:. See https://github.com/mllrsohn/node-webkit-builder/issues/142 and https://github.com/mllrsohn/node-webkit-builder/issues/147

**Comment by chimon2000** [comment] 2015-01-08 22:58
+1 for this issue. I'm running this from Windows. It works fine when I target win, but breaks on osx.

**Comment by sergiovilar** [comment] 2015-01-09 02:59
0.2.3 works!

**Comment by jan4dev** [comment] 2015-01-11 17:42
Same thing here with grunt-node-webkit-builder 1.0.0 and node v0.10.26 on yosemite. Sometimes it will eventually pass. But the app is always damaged.

**Comment by egekhter** [comment] 2015-01-15 19:42
Same error here - eventually builds - usually takes 4 tries.

**Comment by lisposter** [comment] 2015-01-16 01:17
+1

**Comment by developerworks** [comment] 2015-01-18 17:01
Likewise, i was encountered the issue.

**Comment by mdb** [comment] 2015-01-20 16:09
I have encountered this issue too, unfortunately.

@sergiovilar @jwoertink - you each report `0.2.3` working. Just so I'm 100% clear, version `0.2.3` of what?

Thanks!

**Comment by jwoertink** [comment] 2015-01-20 16:12
`0.2.3` of grunt-node-webkit-builder

**Comment by shenzhuxi** [comment] 2015-01-20 17:50
I got this problem with Info.plist file. 
```
chmod 33279 on app/Contents/Resources/app.nw/Info.plist failed after copying, ignoring
```

**Comment by tphalp** [comment] 2015-01-20 21:24
Same problem here, OS X 10.10.1, `grunt-node-webkit-builder 1.0.0`, using `node-webkit-builder 1.0.6`

It will eventually work, but usually takes a few tries.

**Comment by gyzerok** [comment] 2015-01-28 04:28
+1

**Comment by SSilence** [comment] 2015-01-28 11:13
same error on windows: filename of download changed: http://dl.nwjs.io/v0.12.0-alpha2/nwjs-v0.12.0-alpha2-win-x64.zip

**Comment by felixSchl** [comment] 2015-01-28 23:11
If you take that awkward retry loop out, it fails every time for me - means I can reproduce reliably. That retry loop is out of place anyway, imo.

**Comment by adam-lynch** [comment] 2015-01-29 11:48
I just published version `1.0.8` of node-webkit-builder. It helps but doesn't fix it 100%. Try 

```
npm cache clean
npm install grunt-node-webkit-builder
```

**Comment by jan4dev** [comment] 2015-02-05 13:01
Me too. No issues since 1.0.8. Good work.

**Comment by adam-lynch** [comment] 2015-02-23 21:58
Closing in favour of https://github.com/mllrsohn/node-webkit-builder/issues/180 & https://github.com/mllrsohn/node-webkit-builder/issues/142

**Closed by adam-lynch** 2015-02-23 21:58 UTC
